apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}-secret
type: Opaque
data:
  mysqlRootPassword: password
  mysqlUser: root
  mysqlPassword: password
  mysqlDatabase: db
